name: testGitBuild
on:
  push:
    branches:
      - main
jobs:

  compile:    
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - run: Start-Process -FilePath "C:\Program Files\4D\4D v20 R4\4D\4D.exe" -ArgumentList "--structure C:\Users\Ouafa\Desktop\testGitBuild\Project\testGitBuild.4DProject", "--user-param compile"
    - run: |
           $compilationResult=cat compilationResult.txt
           if ($compilationResult != "Syntax check Passed"){
           exit 1
           }